// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLHRe4QjmFWtGr5e2z_e4A2uTOmfclQqw',
    appId: '1:41998864727:web:3ce35538b1aa64d54e2e12',
    messagingSenderId: '41998864727',
    projectId: 'weddingtegoa-a5daa',
    authDomain: 'weddingtegoa-a5daa.firebaseapp.com',
    databaseURL: 'https://weddingtegoa-a5daa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'weddingtegoa-a5daa.firebasestorage.app',
    measurementId: 'G-3400M2QNF3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClWAeRj08f1jeILpYm0D3rqnbin8dZJp0',
    appId: '1:41998864727:android:07c6f3303fab921b4e2e12',
    messagingSenderId: '41998864727',
    projectId: 'weddingtegoa-a5daa',
    databaseURL: 'https://weddingtegoa-a5daa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'weddingtegoa-a5daa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA50C2xVZkKe2vU_60ww9HH9obWYG3R8sk',
    appId: '1:41998864727:ios:abc21180ce2179904e2e12',
    messagingSenderId: '41998864727',
    projectId: 'weddingtegoa-a5daa',
    databaseURL: 'https://weddingtegoa-a5daa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'weddingtegoa-a5daa.firebasestorage.app',
    iosBundleId: 'com.example.machineLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA50C2xVZkKe2vU_60ww9HH9obWYG3R8sk',
    appId: '1:41998864727:ios:abc21180ce2179904e2e12',
    messagingSenderId: '41998864727',
    projectId: 'weddingtegoa-a5daa',
    databaseURL: 'https://weddingtegoa-a5daa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'weddingtegoa-a5daa.firebasestorage.app',
    iosBundleId: 'com.example.machineLearning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLHRe4QjmFWtGr5e2z_e4A2uTOmfclQqw',
    appId: '1:41998864727:web:75ce72e76057bd874e2e12',
    messagingSenderId: '41998864727',
    projectId: 'weddingtegoa-a5daa',
    authDomain: 'weddingtegoa-a5daa.firebaseapp.com',
    databaseURL: 'https://weddingtegoa-a5daa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'weddingtegoa-a5daa.firebasestorage.app',
    measurementId: 'G-RL7RQMHEWM',
  );
}
